#ifndef __TWUNIT_STATUS_H__
#define __TWUNIT_STATUS_H__ 1

#include "twunit_colors.h"

#define TWUNIT_STATUS_PASS "pass"
#define TWUNIT_STATUS_PASS_COLOR TWUNIT_COLOR_GREEN

#define TWUNIT_STATUS_FAIL "fail"
#define TWUNIT_STATUS_FAIL_COLOR TWUNIT_COLOR_RED

#define TWUNIT_STATUS_WARN "warn"
#define TWUNIT_STATUS_WARN_COLOR TWUNIT_COLOR_YELLOW

#define TWUNIT_STATUS_SKIP "skip"
#define TWUNIT_STATUS_SKIP_COLOR TWUNIT_COLOR_WHITE

#endif/*__TWUNIT_STATUS_H__*/
